version: 0.2
BundleType: YAML
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - export BUCKET=auto-server
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml