version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - python -m pip install --upgrade pip
      - virtualenv .env
      - .env/scripts/activate
      - pip install requirements.txt
      - export BUCKET=auto-server
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml