import os

from dotenv import load_dotenv

load_dotenv()

APP_NAME = os.getenv("APP_NAME")
APP_DIR = os.getenv("APP_DIR")
DOCKERFILE = os.getenv("DOCKERFILE")
DIGITALOCEAN_API_TOKEN = os.getenv("DIGITALOCEAN_API_TOKEN")
DIGITALOCEAN_REGION_SLUG = os.getenv("DIGITALOCEAN_REGION_SLUG")
PRIVATE_KEY_PASSPHRASE = os.getenv("PRIVATE_KEY_PASSPHRASE")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_REGION_ID = os.getenv("AWS_REGION_ID")
AWS_OUTPUT_FORMAT = os.getenv("AWS_OUTPUT_FORMAT")


S3_FOLDER = APP_NAME

SSH_KEY_NAME = f"{APP_NAME}-key"
SSH_KEY_FILE_NAME = f"id_rsa"
S3_SSH_KEY_FILE_PATH = f"{S3_FOLDER}/{SSH_KEY_NAME}"

ARCHIVE_FILE_NAME = f"{APP_NAME}.tar.gz"
S3_ARCHIVE_FILE_PATH = f"{S3_FOLDER}/{ARCHIVE_FILE_NAME}"

all_settings = [
    APP_NAME,
    APP_DIR,
    ARCHIVE_FILE_NAME,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    DOCKERFILE,
    DIGITALOCEAN_API_TOKEN,
    DIGITALOCEAN_REGION_SLUG,
    PRIVATE_KEY_PASSPHRASE,
    S3_ARCHIVE_FILE_PATH,
    S3_BUCKET_NAME,
    S3_FOLDER,
    S3_SSH_KEY_FILE_PATH,
    SSH_KEY_NAME,
    SSH_KEY_FILE_NAME,
]
